In [1]:
import pandas as pd
import numpy as np

In [25]:
file_23_cannabis = pd.read_excel("20231.2_Prevalence_of_drug_use_in_the_general_population_including_NPS_national_data.xlsx",skiprows=2, sheet_name=0)
file_23_cocaine = pd.read_excel("20231.2_Prevalence_of_drug_use_in_the_general_population_including_NPS_national_data.xlsx",skiprows=2, sheet_name=1)
file_23_amphetamines = pd.read_excel("20231.2_Prevalence_of_drug_use_in_the_general_population_including_NPS_national_data.xlsx",skiprows=2, sheet_name=2)
file_23_ecstasy = pd.read_excel("20231.2_Prevalence_of_drug_use_in_the_general_population_including_NPS_national_data.xlsx",skiprows=2, sheet_name=3)
file_23_prescription_stimulants = pd.read_excel("20231.2_Prevalence_of_drug_use_in_the_general_population_including_NPS_national_data.xlsx",skiprows=2, sheet_name=4)
file_23_opioids = pd.read_excel("20231.2_Prevalence_of_drug_use_in_the_general_population_including_NPS_national_data.xlsx",skiprows=2, sheet_name=5)
file_23_opiates = pd.read_excel("20231.2_Prevalence_of_drug_use_in_the_general_population_including_NPS_national_data.xlsx",skiprows=2, sheet_name=6)
file_23_prescription_opioids = pd.read_excel("20231.2_Prevalence_of_drug_use_in_the_general_population_including_NPS_national_data.xlsx",skiprows=2, sheet_name=7)
file_23_tranquillizers_and_sedatives = pd.read_excel("20231.2_Prevalence_of_drug_use_in_the_general_population_including_NPS_national_data.xlsx",skiprows=2, sheet_name=8)
file_23_NPS = pd.read_excel("20231.2_Prevalence_of_drug_use_in_the_general_population_including_NPS_national_data.xlsx",skiprows=2, sheet_name=9)

In [23]:
file_23_cannabis

,Unnamed: 0,Region,Sub-region,Country/Territory,Best,Low,High,Male,Female,Year,Age,Source,Method,Adjustment/\n notes,Specific notes
0,NaN,Africa,East Africa,Kenya,1.20,NaN,NaN,2.1,0.3,2016.0,15-64,ARQ,HHS,NaN,NaN
1,NaN,NaN,NaN,Kenya,2.10,0.30,4.00,NaN,NaN,2007.0,15-65,Govt,HHS,"b, e",NaN
2,NaN,NaN,NaN,Kenya,7.10,NaN,NaN,NaN,NaN,2004.0,15-64,"ARQ, NGO, Council of Europe","SS, A","c, d, e, f",NaN
3,NaN,NaN,NaN,Madagascar,9.10,NaN,NaN,NaN,NaN,2004.0,15-64,ARQ,"SS, A","d, e",NaN
4,NaN,NaN,NaN,Mauritius,1.08,NaN,NaN,NaN,NaN,2009.0,15-54,Government source,NaN,a,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,NaN,NaN,NaN,New Zealand,14.60,13.40,15.70,18.2,11.3,2008.0,16-64,Government source,HHS,NaN,2007/08 New Zealand Alcohol and Drug Use Survey
392,NaN,NaN,NaN,New Zealand,14.60,NaN,NaN,NaN,NaN,2007.0,16-64,Government source,HHS,NaN,NaN
393,NaN,NaN,NaN,New Zealand,13.25,NaN,NaN,NaN,NaN,2006.0,15-64,ARQ,HHS,a,NaN
394,NaN,NaN,Melanesia,Fiji,5.08,3.04,7.12,NaN,NaN,2004.0,15-64,Government source,SS,"d, e",NaN
395,NaN,Except where the prevalence values are taken f...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
def fill_in_regions(file_23, idx):
    last_region = ""
    for index in file_23.index:
        if not pd.isna(file_23.iloc[index, idx]):
            last_region = file_23.iloc[index, idx]
        else:
            file_23.iloc[index, idx] = last_region
    return file_23

In [62]:
def clean_file(file, drug):
    filled_in_regions = fill_in_regions(file, 1)
    drop_non_europe = filled_in_regions[filled_in_regions["Region"]=="Europe"]
    drop_columns = drop_non_europe.iloc[:,3:-5]
    int_year = drop_columns.astype({"Year": int})
    drop_gender = int_year.drop(columns=["Male", "Female", "Low", "High"])
    year_after_2020 = drop_gender[drop_gender["Year"]>=2020]
    added_type = year_after_2020.assign(Metabolite=drug) 
    renamed = added_type.rename(columns={'Country/Territory': 'Country', 'Best':'Percentage of the population'})
    dropped_nan =  renamed.dropna()
    return dropped_nan.set_index(["Country", "Year", "Metabolite"])

In [80]:
cannabis_df = clean_file(file_23_cannabis, "cannabis")
cocaine_df = clean_file(file_23_cocaine, "cocaine")
amphetamines_df = clean_file(file_23_amphetamines, "amphetamine")
ecstasy_df = clean_file(file_23_ecstasy, "MDMA")
prescription_stimulants_df = clean_file(file_23_prescription_stimulants, "Prescription Stimulants")
opioids_df = clean_file(file_23_opioids, "Opioids")
opiates_df = clean_file(file_23_opiates, "Opiates")
prescription_opioids_df = clean_file(file_23_prescription_opioids, "Prescription Opioids")

Empty DataFrame
Columns: [Percentage of the population]
Index: []

In [78]:
def clean_file_t_and_s(file):
    filled_in_regions = fill_in_regions(file, 1)
    drop_non_europe = filled_in_regions[filled_in_regions["Region"]=="Europe"]
    drop_columns = drop_non_europe.iloc[:,3:-3]
    int_year = drop_columns.astype({"Year": int})
    drop_gender = int_year.drop(columns=["Male", "Female", "Age"])
    year_after_2020 = drop_gender[drop_gender["Year"]>=2020]
    added_type = year_after_2020.assign(Metabolite="Tranquillizers and sedatives") 
    renamed = added_type.rename(columns={'Country/Territory': 'Country', 'Total':'Percentage of the population'})
    dropped_nan =  renamed.dropna()
    return dropped_nan.set_index(["Country", "Year", "Metabolite"])
 
tranquillizers_and_sedatives_df = clean_file_t_and_s(file_23_tranquillizers_and_sedatives)
tranquillizers_and_sedatives_df

                                                                      Percentage of the population
Country                            Year Metabolite
Latvia                             2020 Tranquillizers and sedatives                      4.900000
Lithuania                          2021 Tranquillizers and sedatives                      1.400000
Netherlands                        2020 Tranquillizers and sedatives                      3.500000
Norway                             2021 Tranquillizers and sedatives                      0.100000
Spain                              2020 Tranquillizers and sedatives                      1.300000
Sweden                             2021 Tranquillizers and sedatives                      2.300000
United Kingdom (England and Wales) 2021 Tranquillizers and sedatives                      0.386212

In [96]:
def clean_file_nps(file):
    filled_in_regions = fill_in_regions(file, 2)
    drop_non_europe = filled_in_regions[filled_in_regions["Region"]=="Europe"]
    drop_columns = drop_non_europe.iloc[:,4:-2]
    drop_columns["Year"] = pd.to_numeric(drop_columns["Year"], errors='coerce')
    drop_columns = drop_columns.dropna(subset=["Year"])
    int_year = drop_columns.astype({"Year": int})
    drop_gender = int_year.drop(columns=["Unnamed: 7", "Unnamed: 8", "Past year", "Unnamed: 10",
                                         "Unnamed: 11", "Past Month", "Unnamed: 13", "Unnamed: 14"])
    year_after_2020 = drop_gender[drop_gender["Year"]>=2020]
    renamed = year_after_2020.rename(columns={'Country/Territory': 'Country', 'Lifetime':'Percentage of the population', 'Substance':'Metabolite'})
    renamed['Metabolite'] = renamed['Metabolite'].str.lower()
    dropped_nan =  renamed.dropna()
    return dropped_nan.set_index(["Country", "Year", "Metabolite"])
 
NPS_df = clean_file_nps(file_23_NPS)
NPS_df

                                                               Percentage of the population
Country                            Year Metabolite
Bulgaria                           2020 synthetic cannabinoids                          0.6
Lithuania                          2021 synthetic cannabinoids                          0.5
Spain                              2020 synthetic cannabinoids                          0.6
Netherlands                        2020 ketamine                                        2.5
Spain                              2020 ketamine                                        0.9
United Kingdom (England and Wales) 2021 ketamine                                   4.122352
Bulgaria                           2020 nps                                             0.6
Latvia                             2020 nps                                             0.3
Lithuania                          2021 nps                                             1.4
Netherlands                        2021 4-fa                                            2.1
Norway                             2021 nps                                             0.5
                                   2020 nps                                             0.2
Spain                              2020 nps                                             1.7
United Kingdom (England and Wales) 2021 nps                                        3.055297
                                        mephedrone                                 1.427872

In [97]:
UN_df = pd.concat([cannabis_df, cocaine_df, amphetamines_df, ecstasy_df, prescription_stimulants_df, opioids_df, opiates_df, prescription_opioids_df, tranquillizers_and_sedatives_df, NPS_df], ignore_index=False,axis=0)

In [99]:
UN_df.to_csv("../UN_world_drug_report.csv")
UN_df

                                                   Percentage of the population
Country                            Year Metabolite
Bulgaria                           2020 cannabis                            2.4
Austria                            2020 cannabis                            6.3
Czechia                            2020 cannabis                           11.1
Denmark                            2021 cannabis                            6.3
Latvia                             2020 cannabis                            3.9
...                                                                         ...
Norway                             2021 nps                                 0.5
                                   2020 nps                                 0.2
Spain                              2020 nps                                 1.7
United Kingdom (England and Wales) 2021 nps                            3.055297
                                        mephedrone                     1.427872

[90 rows x 1 columns]